title: "OpenLumi archive | downloads | Xiaomi DGNWG05LM | Aqara ZHWG11LM"
email:
description: ""

remote_theme: openlumi/wiki
baseurl: "/archive"

minima:
  search_path: /archive/search.html
  social_links:
    telegram: xiaomi_gw_hack
    github: openlumi
